micronaut:
  application:
    name: tripservice

netty:
  default:
    allocator:
      max-order: 3

foo:
  foo: ${FOO}

geoapify:
  # This is no secure. This is a secret and must be retrieved from
  # a secret manager or env vars.
  apiKey:
    07dab08fd2da4d0eb54455ac01f2f920
  http:
    scheme: http
    host: api.geoapify.com
    port: 80
    endpoint: v1/geocode/search

datasources:
  default:
    url: ${DB_JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
    dialect: MYSQL
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000  # En milisegundos

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop # Make this configurable depending on the environment

flyway:
  datasources:
    default:
      enabled: false

http-get-user-by-id:
  scheme: http
  host: ${CORE_SERVICE_HOST:api.roadlink.com.ar}
  port: ${CORE_SERVICE_PORT:80}
  endpoint: users/{userId}
http-get-user-trust-score:
  scheme: http
  host: ${CORE_SERVICE_HOST:api.roadlink.com.ar}
  port: ${CORE_SERVICE_PORT:80}
  endpoint: users/{userId}/user_trust_score
http-post-feedback-solicitude:
  scheme: http
  host: ${CORE_SERVICE_HOST:api.roadlink.com.ar}
  port: ${CORE_SERVICE_PORT:80}
  endpoint: users/{userId}/feedback_solicitudes
